### ISSUE TITLE
Not Compressing (After compress file is unable to open)

### ISSUE THREAD

**Issue by vinay6** [AbedElazizShe/LightCompressor#100]
Hi,

I have tried to compress recording video,  compress is successful but after compress video file is blank 

Device  Moto Fusion Plus
OS = Android 10

Device  = One Plus
OS = Android 11

**Comment by AbedElazizShe** [comment]
Hi @vinay6 , could you please share a sample video [upload to google drive for example and share it with me]? And please confirm that you're using the latest version.

Thank you

**Comment by AbedElazizShe** [comment]
This issue is closed due to inactivity.
