### ISSUE TITLE
video is burst or laggy after compressed

### ISSUE THREAD

**Issue by akbardzulfikar** [AbedElazizShe/LightCompressor#101]
hello, i have a problem when compressing video with this configuration, the video looks like burst, some frame are lost, please help. 

using camera2Api, with configuration:
video encoder: mpeg_4
audio encode : AAC

https://user-images.githubusercontent.com/20625376/145822363-f2974540-8961-4a8b-a9de-7d58660c114f.mp4

device : realme 3 pro
os: android 10

thank you

**Comment by akbardzulfikar** [comment]
https://user-images.githubusercontent.com/20625376/145824660-9d973213-f7e3-46a6-b4bf-b3c5d9266419.mp4

another sample of video

**Comment by akbardzulfikar** [comment]
https://user-images.githubusercontent.com/20625376/145825126-386e2de0-cdb8-48da-b817-912cb3942d95.mp4

g

**Comment by AbedElazizShe** [comment]
Hi @akbardzulfikar, sorry for the late reply. Could you please share the original video and the device used for compression?
You can try version 1.2.0 as well, where I modified the I-frame rate, this could've fixed it.

thank you.
