### ISSUE TITLE
Incompatibility between Android and IOS

### ISSUE THREAD

**Issue by songzhili** [AbedElazizShe/LightCompressor#102]
Hi,
There is an incompatibility between Android and IOS. Some mobile phones upload videos to the server after compressing them. The apple system will have a green screen or can't play them. Both mobile phones and Macs have this problem. There is no problem with Android and web pages

**Comment by songzhili** [comment]
And after the video compression, the video will jump frames, and the 10 second video will be broadcast in about 4 seconds

**Comment by AbedElazizShe** [comment]
Hi @songzhili could you please share a sample video (original and after compression) and let me know which phones you're using so I can investigate. Different phones could have different behaviours and issues. Thanks a lot.

**Comment by songzhili** [comment]
https://user-images.githubusercontent.com/18653713/154007110-ced0945d-84df-4264-980e-690309cf2569.mp4


https://user-images.githubusercontent.com/18653713/154007138-cea1bf06-0052-4db1-997c-7d09fcfe0273.mp4

The above two videos are the problems after compression. There is no original video and the problems found online

**Comment by adurandet** [comment]
Not fixed. 
I have the same issue with 1.3.1 compressing on Pixel 6 and reading on iOS or Mac.
