### ISSUE TITLE
sync Compressor

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [AbedElazizShe/LightCompressor#106]
I want to edit the video inside ViewPager like Telegram, so that several videos are compressed or cut at the same time

Is it possible to add capability compress at the sync Thread?

**Comment by AbedElazizShe** [comment]
I added support for multiple video compression in v1.1.0. Please try it out and let me know if you face any issues.

There are lots of breaking changes in this version, please see what's new in v1.1.0 section in README before updating.

Thank you.

**Comment by nikhilrfitplus** [comment]
U have added multiple video support, but it is again compressing the videos in sequential manner only, not parallel. Please provide a way so that videos will be compressed parallely.

**Comment by AbedElazizShe** [comment]
I added support for multiple video compression in v1.1.1. Please try it out and let me know if you face any issues.

There are lots of breaking changes in this version, please see what's new in v1.1.1 section in README before updating.

Thank you.

**Comment by nikhilrfitplus** [comment]
It's working. Thank you.
Will get back if our QA finds any issues
