### ISSUE TITLE
How to use it in a Android project based Jave?

### ISSUE THREAD

**Issue by liwuchen** [AbedElazizShe/LightCompressor#107]
I have added this in build.gradle, but still can not use any method in my project. Does I need any other configrations?

` implementation 'com.github.AbedElazizShe:LightCompressor:1.0.1'`

**Comment by AbedElazizShe** [comment]
Hi @liwuchen and @gokhanaltun what is the problem you're facing?

`       VideoCompressor.start(
                            getApplicationContext(), 
                            uri, 
                            null // src path, 
                            desFile.getPath(), 
                            null // streamablefile,
                            new CompressionListener() {
                                @Override
                                public void onStart() {

                                }

                                @Override
                                public void onSuccess() {
                                   
                                }

                                @Override
                                public void onFailure(String message) {
                          
                                }

                                @Override
                                public void onProgress(float percent) {

                                }

                                @Override
                                public void onCancelled() {

                                }
                            },
                            new Configuration(
                                    VideoQuality.MEDIUM,
                                    24, /*frameRate: int, or null*/
                                    true, /*isMinBitrateCheckEnabled*/
                                    3677198, /*videoBitrate: int, or null*/
                                    false, /*disableAudio: Boolean, or null*/
                                    false, /*keepOriginalResolution: Boolean, or null*/
                                    360.0, /*videoWidth: Double, or null*/
                                    480.0 /*videoHeight: Double, or null*/
                            ));`

Something like this should work.

**Comment by gokhanaltun** [comment]
Hi, @AbedElazizShe 

Even though I added the dependency, I couldn't access the VideoCompressor class and realized that the problem was with my gradle files.

There was no "allprojects" section in my project-level build.gradle file and I was getting an error when I added it. 
To solve this problem I edited my "settings.gradle" file as below and now everything works. Thanks.

Before:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "Project Name"
include ':app'
```

After:
```
import org.gradle.api.initialization.resolve.RepositoriesMode

dependencyResolutionManagement {

    repositories {
        google()
        repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
        mavenCentral()
        maven { url 'https://jitpack.io' }
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "Project Name"
include ':app'
```

**Comment by AbedElazizShe** [comment]
Thank you @gokhanaltun I really forgot to add this part to README as i faced it myself after upgrading gradle. I added it now.
