### ISSUE TITLE
If i want compress with the min bittate,how should i do?

### ISSUE THREAD

**Issue by urtheone** [AbedElazizShe/LightCompressor#108]

**Comment by urtheone** [comment]
`new Configuration(
                        VideoQuality.VERY_LOW,
                        null, /*frameRate: int, or null*/
                        false,
                        2 * 1024 * 1024, /*videoBitrate: int, or null*/
                        false/*disableAudio: Boolean, or true or false*/
                )`  is that right?

**Comment by AbedElazizShe** [comment]
Hi @urtheone, yes VideoQuality.VERY_LOW is the lowest bitrate which the library converts to original bitrate * 0.1. Does that suit your needs?

**Comment by urtheone** [comment]
> Hi @urtheone, yes VideoQuality.VERY_LOW is the lowest bitrate which the library converts to original bitrate * 0.1. Does that suit your needs?

Yes, the parameter I chose was it, but I found that the compression time is hardly shortened. So I set the third parameter myself: 2 * 1024 * 1024, but when I set this, my previous video began to report errors: 
`onFailureThe provided bitrate is smaller than what is needed for compression try to set isMinBitRateEnabled to false.`
 I changed the parameter to null, and the error message did not disappear.

**Comment by AbedElazizShe** [comment]
The compression time is not affected by the quality, it is usually goes side by side with the length of the video or when the bitrate is very low. That's why i have 2mb bitrate check.

 I will work on audio compression improvement in the near future is that's the issue you're facing.

Thank you.
