### ISSUE TITLE
Feature Request: Make Library Available Backward Support Like API 15

### ISSUE THREAD

**Issue by varun7952** [AbedElazizShe/LightCompressor#109]
Hi, We shifted our project from Sillicompressor to LightCompressor recently but our product is targeting API version 15 also and totally based on Java, If it's possible can you please make it backward compatible. So it can be available to majority of Java users with API 15+

Thanks

**Comment by AbedElazizShe** [comment]
@varun7952 Hi, Thank you for using LightCompressor library. 

API version 15 is very old to be supported. I have stopped supporting anything below 21, 4 years ago. Maybe you should consider updating. 

I am wondering if you have users at the moment using APIs 15 - 19? It would be interesting to know.

![versions](https://user-images.githubusercontent.com/20614470/150674792-ffa46902-0421-4ac5-80ec-94f393f3ff09.PNG)

**Comment by varun7952** [comment]
@AbedElazizShe Thanks for the reply. To be true we see only few users on API 15-16 but from API 17 We still able to see good amount of users and if you notice Whatsapp,Telegram,Instagram and others they are still targeting lowest version of android, Nobody wants to leave their users behind if they have older android version. See if you can make it backward compatible for specially for the Java users. Thx

**Comment by varun7952** [comment]
Can you share code in java so i will try to fork this for backward compatibility?

**Comment by AbedElazizShe** [comment]
Hi @varun7952 , it's lots of work to enable support and test. Considering that api 21 covers 98% of devices, i will not spend time to add support for 2%.

Thank you
