### ISSUE TITLE
Unable to Compress multiple videos parallely

### ISSUE THREAD

**Issue by nikhilrfitplus** [AbedElazizShe/LightCompressor#110]
Thanks for yesterday's commit which is now allowing to pass list of file URIs. But, my core requirement is to get the files compressed in parallel. When i call VideoCompressor.start(.. for the 2nd time, the 1st compression task is getting terminated and calling the successCallBack method, and then the 2nd compression task is starting.
Please add a provision to compress the files parallely or allow to create multiple objects/instances of VideoCompressor class

**Comment by AbedElazizShe** [comment]
Hi @nikhilrfitplus updated in 1.1.1. Please let me know if you have any issues as I only tested it in a small set of devices.

**Comment by nikhilrfitplus** [comment]
Hi AbedElazizShe

Thanks for the prompt reply & instant fix.
It's working now as per my unit test. We have scheduled a QA test tomorrow.
Will let you know if we come across any issues.

Regards,
Nikhil
