### ISSUE TITLE
unexpected CodecException when working on large files

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [AbedElazizShe/LightCompressor#111]
Hi 
when I use this library in my project , I face an exception of type CodecException in the following place:

Compressor -> encoder.configure

and with following message :

mDiagnosticInfo : android.media.MediaCodec.error_neg_5001
detailMessage : Error 0xffffec77

When occurring the mentioned exception, onSuccess method of CompressionListener is called with the size 0!

Mentioned problem happens when working with large videos not the small ones. The information of one of them is mentioned below:
resolution: 1920*1080
size: 2.6 GB

**Comment by AlirezaGhanbarinia** [comment]
When occurring the mentioned exception, onSuccess method of CompressionListener is called with the size 0!

**Comment by AbedElazizShe** [comment]
@AlirezaGhanbarinia thank you for opening the issue. I certainly haven't tried videos that big :). Can you confirm it is mp4? And does it happen on all testing devices you used?

Thank you

**Comment by AlirezaGhanbarinia** [comment]
I'm really confused, why this happened
when use this library in demo all of process is done , but when I use this library in my project I face an exception

I am using a video taken from the camera of this phone and which has the mp4 extension , same library and same configuration on both project

**Comment by AlirezaGhanbarinia** [comment]
I realized that the problem is related to which part, I propose my solution, maybe it will be useful for one person

When using ExoPlayer next to Mediacodec in a fragment or activity, to use Mediacodec , the player release commands must be called

This problem is more common in Samsung mobile phones

**Comment by AbedElazizShe** [comment]
Thank you @AlirezaGhanbarinia
