### ISSUE TITLE
Remove audio :(

### ISSUE THREAD

**Issue by resistance1404** [AbedElazizShe/LightCompressor#114]
Hi. i use your library in my project but when see the result of compressed file the file has not sound. why? my configuration is :
VideoQuality.MEDIUM,24,false,null,false,false,null,null

**Comment by AlirezaGhanbarinia** [comment]
"Configuration" class has many parameters , if you set true for "disable Audio" parameter ,you removed the video sound,please carefully set value for input parameters , and read below document

https://github.com/AbedElazizShe/LightCompressor#configuration-values

**Comment by AbedElazizShe** [comment]
Thank you @AlirezaGhanbarinia.

@resistance1404 can you share the following in case the problem is something else:

- Sample video [upload to google drive for example and share it with me]
- The testing device(s), let me know how many devices you use and if the problem happens on all of them or just a few.
- Android version.

Thank you.

**Comment by monali0521** [comment]
I got the same issues, audio is gone after compression in some videos though I set false to disable Audio parameter.

I have attached the video. and it is reproducing in different devices and android versions.

https://user-images.githubusercontent.com/87650116/152482582-7f5b9a6f-fe1c-40f6-a38e-847ec50b5ef0.mp4

**Comment by vandat0599** [comment]
Facing the same issue. May I know if this issue is already fixed or not?

**Comment by nikbagde** [comment]
I'm also facing the same issue, after compression sound is gone. I guess it is causing only with java coding, with kotlin it is working fine.

**Comment by hientranea** [comment]
Getting the same issue here. I used the video @monali0521 provided and the compressed file has no sound
- Testing devices: both emulator and physical device, running Android 12
- Library version: `1.1.1` 

Btw, we also got the warning from QuickTime Player when trying to play the output file: `This file contains some media which isn’t compatible with QuickTime Player.`

**Comment by AbedElazizShe** [comment]
Hello @monali0521 @vandat0599 @nikbagde @hientranea, thank you for the details and I apologise for the late reply.

The problem is related to mono vs stereo types. I have fixed the issue and will release 1.2.0 shortly. Please let me know if it is fixed.

**Comment by k41ed** [comment]
not fixed
