### ISSUE TITLE
Video FPS minimum limit at 21 FPS

### ISSUE THREAD

**Issue by Korbpw** [AbedElazizShe/LightCompressor#116]
```
configureWith = Configuration(
    quality = VideoQuality.VERY_LOW,
    isMinBitrateCheckEnabled = true,
    videoWidth = 480.0,
    videoHeight = 320.0,
    frameRate = 12
)
```

Even do my framerate is at 12 on the config it always renders out at 21 FPS and no lower than that ( i counted it on After Effects too )

![image](https://user-images.githubusercontent.com/46784998/153935444-520f94b2-c47d-4662-9901-cbc3968c69dc.png)

**Comment by AbedElazizShe** [comment]
Hi @Korbpw. If i am not mistaken, the value could be reset by the device itself for some cases. And modifying it could require lots of manual work to supply the frames.

I want to remove the support for this until I do some research to determine the best way to implement it. I hope it won't affect your work.

thank you.
