### ISSUE TITLE
SaveAt Internal Storage

### ISSUE THREAD

**Issue by ghasemdev** [AbedElazizShe/LightCompressor#117]
Hi, is there any way to save video in internal storage like `cacheDir` or `fileDir` ?

**Comment by AhsenSaeed** [comment]
Getting same issue?

**Comment by AbedElazizShe** [comment]
Hi @ghasemdev and @AhsenSaeed Thank you for opening this issue. 

I have added a fix to allow you to pass a isExternal (true/false) flag which will save to files dir if it is false.

I will release version 1.2.0 shortly.

Thank you.
