### ISSUE TITLE
Request for commercial usage or Apache-2.0 Licensing 

### ISSUE THREAD

**Issue by kathisai** [AbedElazizShe/LightCompressor#119]
HI @AbedElazizShe 

We would like to ship one of our commercial  product with this library, as this library comes under [GPL-3.0 License](https://github.com/AbedElazizShe/LightCompressor/blob/master/LICENSE) we can't proceed further to integrate this library in to our project as per our legal team.  is it possible to make this library to [Apache-2.0 License] ? can we talk about any other options ?

would like to discuss further on this, please feel free to send a DM me on https://twitter.com/kathisaiprathap or email me sai.990880@gmail.com. 

Thanks
Sai Prathap 
Senior Android Engineer

**Comment by AbedElazizShe** [comment]
Hi @kathisai I will change the licence to Apache-2.0 shortly. I can safely do that based on the modifications i've done in the library.

Thank you.
