### ISSUE TITLE
Instance nullpointer

### ISSUE THREAD

**Issue by lucazin** [AbedElazizShe/LightCompressor#12]
VideoCompressor.**INSTANCE**.start(
						Source.getPath(),
						Destination.getPath(),

The instance propery always null.
How can i fix this?

Im using inside a service.

Thanks!

**Comment by AbedElazizShe** [comment]
Thank you for posting this issue.. Could you please share some code. It is working fine on my end!

**Comment by AbedElazizShe** [comment]
Please open the issue if you keep facing it. Will close it for now due to inactivity.
