### ISSUE TITLE
 Some videos report errors ，some not

### ISSUE THREAD

**Issue by mobilewhj** [AbedElazizShe/LightCompressor#124]
java.lang.SecurityException: Permission Denial: reading com.miui.gallery.provider.GalleryOpenProvider uri content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FVideo%2F1637227610592.mp4 from pid=27557, uid=10580 requires the provider be exported, or grantUriPermission()

**Comment by asd3590058** [comment]
![image](https://user-images.githubusercontent.com/41050100/174771658-047fdbdb-c3ce-45f9-ab3e-e793cecff02c.png)
