### ISSUE TITLE
Video shrink issue 

### ISSUE THREAD

**Issue by SaurabhSportido** [AbedElazizShe/LightCompressor#13]
For Video size which fall in below condition

 width >= 960 || height >= 960 -> {
       newWidth = MIN_HEIGHT
       newHeight = MIN_WIDTH
   }

video getting shrink after compress, i think their should be a small correction in this condition
 newWidth = MIN_WIDTH
 newHeight = MIN_HEIGHT

or like other 
newWidth = width * 0.8
newHeight = height * 0.8
 
so please have a look for these type of videos, rest is working fine. 
Thanks for your great work.

**Comment by AbedElazizShe** [comment]
Thank you for raising this concern. I will work on that and will release a new version this weekend. Thank you

**Comment by AbedElazizShe** [comment]
Version 0.5.0 has solved this issue. Thank you :D

**Comment by SaurabhSgs** [comment]
width >= 960 || height >= 960 -> {
                newWidth = (((MIN_HEIGHT * 0.95) / 16).roundToInt() * 16)
                newHeight = (((MIN_WIDTH * 0.95) / 16).roundToInt() * 16)
            }

this logic is not working perfectly for some video, through this condition video is converted from vertical to horizontal mode when compressed.

i think this should be like below condition:
 
                **newWidth** = (((**MIN_WIDTH** * 0.95) / 16).roundToInt() * 16)
                **newHeight** = (((**MIN_HEIGHT** * 0.95) / 16).roundToInt() * 16)

please look into this issue.

**Comment by AbedElazizShe** [comment]
Thank you for spotting this, I will release a new version in a few hours and will notify you

**Comment by AbedElazizShe** [comment]
@SaurabhSgs The issue is fixed in version `0.7.6`.

**Comment by SaurabhSgs** [comment]
@AbedElazizShe Thanks for your quick response with solution.
