### ISSUE TITLE
Video get Burst 

### ISSUE THREAD

**Issue by eduxcellence** [AbedElazizShe/LightCompressor#14]
Please can u share the method not decreasing resolution on ly bitrate according to video size

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue. Could you please provide more details? What do you want to achieve? I'd be happy to do some improvements. Thank you

**Comment by AbedElazizShe** [comment]
Version 0.5.0 will allow you to choose whether to change reslution or not. Read [Usage](https://github.com/AbedElazizShe/LightCompressor#usage) for more information.
