### ISSUE TITLE
Setting isExternal to false does not use saveAt as subfolder

### ISSUE THREAD

**Issue by VincentJoshuaET** [AbedElazizShe/LightCompressor#143]
This is how I compress my video URIs

        VideoCompressor.start(
            context,
            listOf(uri),
            true,
            StorageConfiguration(saveAt = Environment.DIRECTORY_PICTURES, isExternal = false),
            Configuration(VideoQuality.LOW),
            listener
        )

where `Environment.DIRECTORY_PICTURES` = `"Pictures"`

With above, the file gets saved at `/data/data/PACKAGE_NAME/files/FILE_NAME.mp4` instead of `/data/data/PACKAGE_NAME/files/Pictures/FILE_NAME.mp4`

The corresponding source code:

    private fun saveVideoInInternal(
        context: Context,
        videoFileName: String,
        videoFile: File
    ): File {
        context.openFileOutput(videoFileName, Context.MODE_PRIVATE)
            .use { outputStream ->
                FileInputStream(videoFile).use { inputStream ->
                    val buf = ByteArray(4096)
                    while (true) {
                        val sz = inputStream.read(buf)
                        if (sz <= 0) break
                        outputStream.write(buf, 0, sz)
                    }

                }
            }
        return File(context.filesDir, videoFileName)
    }

I think `context.filesDir` should be changed to `context.getExternalFilesDir(Environment.DIRECTORY_PICTURES)` where `Environment.DIRECTORY_PICTURES` is the specified `saveAt` property

**Comment by AbedElazizShe** [comment]
Hi @VincentJoshuaET . Thank you for opening this issue. In the documentation:
"- saveAt: the directory where the video should be saved in. The value will be ignored if isExternal is false."

So if isExternal is false, the library saves in internal storage. Do you want to create a nested folder?

**Comment by charlesgles9** [comment]
@AbedElazizShe 

In your saveVideoFile function in your library you used the ```context.getExternalFilesDir``` function to fetch the storage path but you have to split the string first so the saveAt argument won't work even when the isExternal boolean flag is set to true. Took me a while to realize it was actually saving to the application cache folder rather than the internal public directories.

 ```getExternalFilesDir(null)```  returns a path to the cache folder ```/android/emulated/0/Android/data/my.application.app/```

so we need to split the string and get the substring from index 0 till the last indexOf("Android")

**Comment by charlesgles9** [comment]
This is a function I've come up with that returns the correct path of the sd card 

![Screenshot from 2022-12-12 18-34-28](https://user-images.githubusercontent.com/41951671/207090649-3de5287d-b43d-4737-b234-9066b9b8adcd.png)

**Comment by AbedElazizShe** [comment]
Version 1.3.0 is handling this in a clearer way.
