### ISSUE TITLE
Audio not working in after compressing video

### ISSUE THREAD

**Issue by krunalpatel3** [AbedElazizShe/LightCompressor#144]

**Comment by krunalpatel3** [comment]
after my finding the audio is not working in this version of library  
implementation "com.googlecode.mp4parser:isoparser:1.1.18"

the audio is working in this version of library 
implementation "com.googlecode.mp4parser:isoparser:1.0.6"

if you are facing this issue please downgrade mp4parser library to this below version
 implementation "com.googlecode.mp4parser:isoparser:1.0.6"

**Comment by pankaj9717** [comment]
> mp4parser:isoparser

tried but not working

**Comment by krunalpatel3** [comment]
@pankaj9717 try this implementation "com.googlecode.mp4parser:isoparser:1.0.6"
