### ISSUE TITLE
Save file in specific Storage

### ISSUE THREAD

**Issue by IrfanFadhilah48** [AbedElazizShe/LightCompressor#146]
I have tried to save in AppSpecificStorageConfiguration and onSuccess return 

> /data/user/0/com.x.x/files/sub_folder

how to save to speicific folder? like
> /storage/emulated/0/Android/media/com.x.x/sub_folder

and giving error in logcat
![image](https://user-images.githubusercontent.com/39039612/208834931-c0e00957-ae9d-476a-b227-23e2ae2bcab6.png)

**Comment by AbedElazizShe** [comment]
Version 1.3.0 will have support for this.
