### ISSUE TITLE
Multiple files compress with only one target file name, make it impossible to compress multi files at one time

### ISSUE THREAD

**Issue by moesama** [AbedElazizShe/LightCompressor#147]
Your api provides only multiple files version, but in any storage configuration, there is only one target file name config.
Should the `videoName` field in storage config be a lambda like this?
```kotlin
videoName: (index: Int) -> String
```

**Comment by AbedElazizShe** [comment]
Thank you @moesama , I realised the mistake and added a fix, will be releasing within 24 hours.
