### ISSUE TITLE
Error: open failed: ENOENT (No such file or directory) when saving to subfolder

### ISSUE THREAD

**Issue by VincentJoshuaET** [AbedElazizShe/LightCompressor#148]
https://stackoverflow.com/questions/36088699/error-open-failed-enoent-no-such-file-or-directory

Based on the above, we should call path.mkdirs() to avoid this. Hopefully this can be done by the library.

**Comment by AbedElazizShe** [comment]
@VincentJoshuaET thank you for raising this issue. Yes you're right, I have made the changes and made the process more optimised. I will be pushing a release within 24 hours.

Thanks a lot.
