### ISSUE TITLE
Possible to predict compressed file size

### ISSUE THREAD

**Issue by vedraj360** [AbedElazizShe/LightCompressor#149]
Is it possible to know what will be the size of file after compression before compressing it.

**Comment by tutankhamen-1** [comment]
Yes, you can get a fairly accurate estimate.
File size in GB = bitrate in Mbps * duration in minutes * 0.0075

**Comment by vedraj360** [comment]
Hi thanks for the reply but can you explain a bit more what is **0.0075** here and duration in minutes how to calculate as it will depend on the device I guess

**Comment by tutankhamen-1** [comment]
The duration in minutes refers to the length of the video. You can read more about this formula here:

https://blog.frame.io/2017/03/06/calculate-video-bitrates/

**Comment by vedraj360** [comment]
Cool, Thanks for the help. Appreciated 👍
