### ISSUE TITLE
Enhancement for multiple file name in AppSpecificStorageConfiguration

### ISSUE THREAD

**Issue by HeinXtet** [AbedElazizShe/LightCompressor#150]
Thanks for great library. I would like to mention about the custom filename in AppSpecificStorageConfiguration. Currently library does supports the multiple uri to compressing but the file ovverided with given name for all uri because library supports only one file name 

Example. I pass the list which have two uri and given name in `AppSpecificStorageConfiguration` is **test_compress** and subfolder name is **testFolder**. After compressed uri from list the output is only 1 file inside **testFolder**. 

Hope it update soon. 
Thanks

![Screen Shot 2022-12-28 at 12 58 32 PM](https://user-images.githubusercontent.com/35194626/209765374-312ec102-604a-4477-bb36-514bf8d882e4.png)

**Comment by AbedElazizShe** [comment]
Hi @HeinXtet , thank you for openning this issue. I realised the mistake and have added a fix, I will push a release within 24 hours.

Thanks a lot.
