### ISSUE TITLE
Audio Issue...

### ISSUE THREAD

**Issue by Micoder-dev** [AbedElazizShe/LightCompressor#153]
while building this direct src code after compression there is no issue with audio, but if i try to use in new projects after compression there is no audio, even if i use "disableAudio = false," it dosen't works.

**Comment by AbedElazizShe** [comment]
Hi @Micoder-dev , 

Thank you for raising this issue. Please provide the following so I can invstigate the issue:
- Device name
- Android version
- Video link if possible.

**Comment by Micoder-dev** [comment]
> Hi @Micoder-dev ,
> 
> Thank you for raising this issue. Please provide the following so I can invstigate the issue:
> 
> * Device name
> * Android version
> * Video link if possible.

Hey man thanks for your reply, i solved this issue, the issue is while using another lib 'com.github.AndroidDeveloperLB:VideoTrimmer:6' which is a video trimmer lib, in this lib there is a isoparser which is in version 1.1.22 and in your light compressor the isoparser is 1.0.6 so there is a confilict while using 2 libs at the same time not only this lib even if the i use any other lib which contains isopraser with latest or some other versions, so i have modified the video trimmer lib and now it resolved, i think most of the users stucks here to find the issue...! so please try to update the isoPraser version or any other ways to solve it! THANK YOU!
