### ISSUE TITLE
How to save video at specific folder path Currently it is saving the compressed video in Movie folder.

### ISSUE THREAD

**Issue by kingnightdrifter** [AbedElazizShe/LightCompressor#154]

**Comment by AbedElazizShe** [comment]
Hi @kingnightdrifter , please refer to the documentation for more details, as a summary:

`AppSpecificStorageConfiguration Configuration values`
- videoName: a custom name for the output video.
- subFolderName: a subfolder name created in app's specific storage. The library won't create the subfolder and will throw an exception if the subfolder does not exist.

`SharedStorageConfiguration Configuration values`
- videoName: a custom name for the output video.
- saveAt: the directory where the video should be saved in. Must be one of the following; [SaveLocation.pictures], [SaveLocation.movies], or [SaveLocation.downloads].
