### ISSUE TITLE
Force close in Android 13 

### ISSUE THREAD

**Issue by devluckman** [AbedElazizShe/LightCompressor#157]
I use sample project , is there a solution to this problem? Thanks

**Reason: Input dispatching timed out (2478853 com.abedelazizshe.lightcompressor/com.abedelazizshe.lightcompressor.MainActivity (server) is not responding. Waited 10002ms for FocusEvent(hasFocus=true))**

<img width="1373" alt="Screen Shot 2023-07-03 at 17 27 46" src="https://github.com/AbedElazizShe/LightCompressor/assets/25347788/373dcbe3-01cb-455a-9248-17402966a9ea">

**Comment by AbedElazizShe** [comment]
@devluckman @yangiljae thank you for raising this issue, can you share the devices models where the issue happened?

**Comment by yangiljae** [comment]
@AbedElazizShe The device that occurred is "SM-G986N".  model name : Galaxy S20+

**Comment by devluckman** [comment]
> @devluckman @yangiljae thank you for raising this issue, can you share the devices models where the issue happened?

I use device samsung Note20 Ultra and Galaxy M12

**Comment by yangiljae** [comment]
@AbedElazizShe 
I checked with the new version(1.3.0) and it doesn't happen. thx
