### ISSUE TITLE
Video already compressed

### ISSUE THREAD

**Issue by singhatalpha** [AbedElazizShe/LightCompressor#17]
I downloaded a video from WhatsApp/Instagram, the video is already compressed with very low resolution. If I compress it further and try to play it in macbook, it shows greenish kind of color in the video. Please introduce a feature in your library to check certain stats of a video, if they are low enough, it shouldn't compress the video further.
Thanks in advance.

**Comment by AbedElazizShe** [comment]
Thank you for your feedback. You can do that already by passing `isMinBitrateEnabled = true`. Refer to the code examples [here](https://github.com/AbedElazizShe/LightCompressor#kotlin). This will ensure only videos with bitrate above 2mbps will be compressed. Let me know if that value works fine with your case scenarios.

Thank you
