### ISSUE TITLE
ANR is happening while compressing video starts

### ISSUE THREAD

**Issue by amrreda1995** [AbedElazizShe/LightCompressor#172]
Firebase crashlytics reported that there's some ANR happens because of some block of code running in the main thread.
After Investigation, I found that the compressing library code uses EmptyCoroutineContext which is considered the app main thread.
I made a small Pull Request with a fix for this issue by providing the IO context for kotlin coroutines to force code to be run in the IO thread.

Below, you can find attachments for the ANR in firebase crashlytics
![Screenshot from 2023-09-25 13-42-24](https://github.com/AbedElazizShe/LightCompressor/assets/48790678/230a5621-8290-42fc-8bae-406df23bd207)
![Screenshot from 2023-09-25 13-42-42](https://github.com/AbedElazizShe/LightCompressor/assets/48790678/0eb43a91-4095-4b09-b7a0-c1469fef9e37)

**Also, here are you a Pull Request for a small fix for this small issue**
**https://github.com/AbedElazizShe/LightCompressor/pull/171**

**Comment by AbedElazizShe** [comment]
Thanks a lot for your contribution. I have merged your PR and will release a new version soon.
i am testing on samsung A51 to try to find the potential issue.

**Comment by amrreda1995** [comment]
Great.
Thanks for the approval.
In order to reproduce the issue; try to compress a video with large size.
For me, I was trying to compress 1.5 GB video (UHD quality).
