### ISSUE TITLE
can't find kotlinx.coroutines.CoroutineScope class file

### ISSUE THREAD

**Issue by ladeng** [AbedElazizShe/LightCompressor#19]
can't find kotlinx.coroutines.CoroutineScope class file

**Comment by AbedElazizShe** [comment]
Could you please provide more details? You can start by posting code of build.gradle, how do you call compressor method, and your logcat/build messages.

**Comment by ladeng** [comment]
I solved this problem thanks！
I forgot to do :
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.coroutines}"
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.coroutines}"
