### ISSUE TITLE
Compressor Error

### ISSUE THREAD

**Issue by caiyoufei** [AbedElazizShe/LightCompressor#2]
this video can not compress
https://github.com/caiyoufei/ABase/blob/master/video/cover_frame.mp4

**Comment by caiyoufei** [comment]
![image](https://user-images.githubusercontent.com/11989916/80950667-7ae2c100-8e20-11ea-9769-f4f5e8cafc73.png)

**Comment by AbedElazizShe** [comment]
![Screenshot_20200504-214728](https://user-images.githubusercontent.com/20614470/80975017-25280c00-8e54-11ea-8da1-0b0f1feb69f4.png)

I have fixed this issue. It is intereting that if the generated width/height is not dividable by 2, it will fail. So I am rounding the value to its nearest number dividable by 2.
