### ISSUE TITLE
how to resolve Execution failed for task ':app:checkDebugDuplicateClasses'

### ISSUE THREAD

**Issue by mkazemian** [AbedElazizShe/LightCompressor#20]
When I use the following two libraries simultaneously, I see an error in the build section

`implementation 'com.github.AbedElazizShe:LightCompressor:0.5.0'‍`
 `implementation 'com.github.AndroidDeveloperLB:VideoTrimmer:6'`

But if I comment on any of these libraries, everything works fine How can I fix this problem?

`Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
java.lang.RuntimeException: Duplicate class com.coremedia.iso.AbstractBoxParser found in modulesLightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.SilenceTrackImpl found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)

Duplicate class com.googlecode.mp4parser.authoring.tracks.TextTrackImpl$Line found in modules   LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.h265.H265TrackImpl found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.h265.PicTiming found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.h265.SEIMessage found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.h265.SequenceParameterSetRbsp found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)
Duplicate class com.googlecode.mp4parser.authoring.tracks.h265.VideoParameterSet found in modules LightCompressor-0.5.0-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.5.0) and isoparser-1.1.22.jar (com.googlecode.mp4parser:isoparser:1.1.22)`

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue. It is happening because the 2 libraries are using different versions of isoparser. Could you please try to implement that library as follows;
`    implementation ('com.github.AndroidDeveloperLB:VideoTrimmer:6') {
        exclude  group: 'com.googlecode.mp4parser', module: 'isoparser'
    }
`
And let me know if you can use it that way. 

Thank you

**Comment by mkazemian** [comment]
Thank you for your good response
I explored the library but got a new error :(
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/mp4parser/FileDataSourceViaHeapImpl;
        at com.lb.video_trimmer_library.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.kt:91)
        at com.lb.video_trimmer_library.utils.TrimVideoUtils.startTrim(TrimVideoUtils.kt:69)
        at com.lb.video_trimmer_library.BaseVideoTrimmerView$initiateTrimming$1.execute`

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.googlecode.mp4parser.FileDataSourceViaHeapImpl" on path: DexPathList[[zip file "/data/app/abr.sport.temp-2/base.apk"],nativeLibraryDirectories=[/data/app/abr.sport.temp-2/lib/x86_64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.lb.video_trimmer_library.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.kt:91) 
        at com.lb.video_trimmer_library.utils.TrimVideoUtils.startTrim(TrimVideoUtils.kt:69) 
        at com.lb.video_trimmer_library.BaseVideoTrimmerView$initiateTrimming$1.execute(BaseVideoTrimmerView.kt:187) 
        at com.lb.video_trimmer_library.utils.BackgroundExecutor$Task.run(BackgroundExecutor.kt:200) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: com.googlecode.mp4parser.FileDataSourceViaHeapImpl`

**Comment by AbedElazizShe** [comment]
It seems the libraries cannot work together due to the different versions of the dependencies used. I came accross this [stackoverflow's similar issue](https://stackoverflow.com/questions/51336655/using-different-versions-of-same-library-more-than-one-file-was-found-with-os?rq=1) with the same library. Please have a look.

**Comment by AbedElazizShe** [comment]
Will close this issue for inactivity, please reopen it if you still didn't figure it out.
