### ISSUE TITLE
When the video start play, it takes a long time to start playing

### ISSUE THREAD

**Issue by ladeng** [AbedElazizShe/LightCompressor#22]
When I compress the video and upload it to the server, and then play it,  it takes a long time to start playing
Can you put the moov of the video before mdat when compressing?

**Comment by AbedElazizShe** [comment]
Thank you for the suggestion, I am looking into this, will notify you when it's done.

**Comment by Kunalapk** [comment]
@AbedElazizShe the compressed video is not buffering when played from the server in the android app.
It downloads 100% and then plays.

**Comment by AbedElazizShe** [comment]
@Kunalapk Thank you for reporting this, I haven't tried that myself. I will look into this and solve the issue.

**Comment by Baaaaatz** [comment]
Is this resolved already? Experiencing this while uploading the output to s3 bucket.

**Comment by mradzinski** [comment]
This is extremely important. Most people compress a video and then upload it for later reproduction. If after compression the video needs to be fully downloaded and can't buffer, then the entire point of compressing it gets lost.

**Comment by waterdrake** [comment]
Any updates on this? Would be really useful for streaming.

**Comment by Kunalapk** [comment]
We processed our videos on server(added some meta data in video file) and made them streamable.

**Comment by waterdrake** [comment]
What did you use to do that?

**Comment by Kunalapk** [comment]
used ffmpeg in python

**Comment by Kunalapk** [comment]
We have attached that process to different thread and notified our user "Your video is processing we will send you a notification when it's ready to view", and nope it is not that much heavy. @waterdrake

**Comment by waterdrake** [comment]
@Kunalapk Cool.

Would still be cool if this library could do it! Would save a lot of time and offload the work to the client. Anyone have any ideas how that can be done?

**Comment by Kunalapk** [comment]
of course @waterdrake.

**Comment by AbedElazizShe** [comment]
@waterdrake @Kunalapk thank you for the feedback and the usefull details. Sorry I got really busy and didn't have time to enhance that. I am open to ideas on how the video should be fixed to achieve what you want. @Kunalapk If I can know what is the meta data added, I could just handle that in the library during compression.

Thank you.

**Comment by akshayspaceo** [comment]
@AbedElazizShe any update on this problem?

**Comment by chnouman** [comment]
this is a serious issue

**Comment by chnouman** [comment]
@AbedElazizShe please help man

**Comment by AbedElazizShe** [comment]
@chnouman I am working on this now. Could you please share what you use for testing ? Is there a specific streaming type or protocol you're using? 

I am compressing using pixel devices and I don't have issues streaming. Is there something specific I should know about?

**Comment by chnouman** [comment]
@AbedElazizShe I'm using different devices like readme and Samsung. I compress the video and upload it to the server. I have a logic to only compress video if it is more than 20mb. 

I uploaded 2 videos one with compression one without compression. Now from android app I get the list of videos, when I play the video which is compressed it take 8-15 seconds to start playing but the other video which is not compressed take only 1-3 seconds to start playing.

**Comment by chnouman** [comment]
@AbedElazizShe let me know if you need any other thing from me or I can help here. I'm simply using a VPS server with PHP 7 for my backend apis. Nothing fancy.

**Comment by AbedElazizShe** [comment]
@chnouman please try version 0.9.5. I added an ugly fix but it should get the job done, the catch that you need to pass another path. So in addition to [destPath], pass [streamableFile] path as string too. When done, the library will delete one video that reference [destPath] and the desired video will have streamableFile reference. 

Let me know if there is any issues. Close the issue if it solves the problem.

**Comment by chnouman** [comment]
@AbedElazizShe thank you for your efforts we are really appreciating your time and effort for open source contribution. It is now loading the preview quickly and time has also improved but compared to normal video it is still taking some time. I'm attaching a video which is showing a comparison. The first video I played is normal(without compression size is around 17MB. The second video I'm playing is 13 MB and is a compressed one. I hope this will help you to improve it further. Let me know if I can provide you any further details to help in it.


https://user-images.githubusercontent.com/15146352/128966035-f5a0e7e5-cdc6-4294-b1f7-4797cf928eea.mp4

**Comment by AbedElazizShe** [comment]
I have tried multiple ways to do that, and it seems the results won't be satisfactory. I believe for having high quality streaming services, videos could be processed on server side to move the moov to top. The flexibility on the method i am using is not that helpful and the documentation for media codec is really bad. 

I will not spend time anymore on this feature so I can focus on fixing major bugs and improve the speed of compression. 

If anyone with better knowledge and understanding of how this work and is willing to help, feel free to open a PR or contact me to discuss a solution. 

Thank you.
