### ISSUE TITLE
Video compress not working properly (see issue attached here)

### ISSUE THREAD

**Issue by rodrigowpl** [AbedElazizShe/LightCompressor#23]
Stacktrace:
![image](https://user-images.githubusercontent.com/18172307/89111031-7467e380-d427-11ea-8a6d-71e51963db1d.png)

Here's my code and debug attached print:
![image](https://user-images.githubusercontent.com/18172307/89111454-5650b200-d42c-11ea-8c52-a41be13f4133.png)

I'm trying to compress a video soon after recording using the camera

Am I missing something or do you need more detail? 

Thanks!

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue. Did you add the permissions needed that are stated in [Usage](https://github.com/AbedElazizShe/LightCompressor#usage) ?

**Comment by rodrigowpl** [comment]
Yes, here is my manifest
![image](https://user-images.githubusercontent.com/18172307/89133560-320bd880-d4f3-11ea-9379-281f395f99f6.png)

**Comment by AbedElazizShe** [comment]
Could you please try the latest version of the library 0.6.2 and print out the failure message onFailure()?

**Comment by rodrigowpl** [comment]
@AbedElazizShe sure, I will be able to do it at the end of the day today

**Comment by rodrigowpl** [comment]
@AbedElazizShe sorry about the delay to answer, right now I'm moving to a new apartment to it's crazy here :D 

Here is the log:
![image](https://user-images.githubusercontent.com/18172307/89450469-fa8a6f80-d730-11ea-9f7e-059ab07ebde6.png)

I have 100% the permission is right, so probably is something with the video path, what would be your guess?

Thanks!

**Comment by AbedElazizShe** [comment]
@rodrigowpl thank you for your comment, I hope everything is fine now on your side. 

We can try 2 things, 1- is to try the sample app of the library and see if it works, 2- if it is possible to share one of these videos with me so I can debug on my side, with different cameras and devices, the possibilities can be huge. I will try to figure it out by today if you could share the video in case (1) didn't work.

If by any chance you have your project openely on github, I can have a look too.

Thank you :D

**Comment by rodrigowpl** [comment]
@AbedElazizShe Unfortunately the project that I'm using it I can't share, but I will try to provide you an open-source playground testing the same scenario with the video this weekend

**Comment by AbedElazizShe** [comment]
@rodrigowpl thank you, I'd appreciate that

**Comment by AbedElazizShe** [comment]
Just curious, are you using `ACTION_PICK` or `ACTION_GET_CONTENT` when picking up the video ?

**Comment by rodrigowpl** [comment]
@AbedElazizShe no, I'm using Camera and getting directly from there

**Comment by AbedElazizShe** [comment]
Yes it is definitely because of the path, MediaMetadataRetriever's setDataSource() is throwing an IllegalArgumentException(). A play ground app that you can share will help me handle this scenario. Will try to do one myself and to figure out such a case.

Thank you for the details

**Comment by rodrigowpl** [comment]
@AbedElazizShe I'm still trying to figure out the issue, and trying to have time to get a playground app done. Sorry about the delay

**Comment by rodrigowpl** [comment]
@AbedElazizShe Just an update

The path actually is also correct. The issue was because I was using DIRECTORY_DOCUMENTS, and in you example you are using DIRECTORY_DOWNLOADS, I've just changed this and it worked

this point in my code:
![image](https://user-images.githubusercontent.com/18172307/90277077-4fb63780-de3b-11ea-9874-60880c7ccd82.png)

Do you know why?

**Comment by AbedElazizShe** [comment]
That's weird, it works fine with `DIRECTORY_DOCUMENTS` on my end. Were you using `getExternalStoragePublicDirectory()` before ? Because the generate path in your previous screenshots does not look like it.

**Comment by rodrigowpl** [comment]
@AbedElazizShe before I was using the same as yours

**Comment by rodrigowpl** [comment]
let me do some more tests and I will let you know to close the issue

**Comment by rodrigowpl** [comment]
@AbedElazizShe just figured out the problem!

My issue was really the path, the problem was `getExternalStoragePublicDirectory` was returning the correct path but the one I wasn't giving permission. Using Android Context API solved the problem. See the image attached comparing just for out curiosity:

![image](https://user-images.githubusercontent.com/18172307/90322002-3d182d00-df25-11ea-9661-fde4a63949b1.png)

Your library is working pretty well. Feel free to close the issue, thanks for all your support!

**Comment by AbedElazizShe** [comment]
Thank you for posting this. I am sure it will help others with similar cases.
