### ISSUE TITLE
Duplicate class when using library with iso parser already present in application

### ISSUE THREAD

**Issue by pdAfy51** [AbedElazizShe/LightCompressor#25]
Duplicate class com.coremedia.iso.AbstractBoxParser found in modules jetified-LightCompressor-0.6.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.6.2) and jetified-isoparser-1.1.20.jar (com.googlecode.mp4parser:isoparser:1.1.20)
Duplicate class com.coremedia.iso.AbstractBoxParser$1 found in modules jetified-LightCompressor-0.6.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.6.2) and jetified-isoparser-1.1.20.jar (com.googlecode.mp4parser:isoparser:1.1.20)

**Comment by prashantd123** [comment]
remove other video or image compressing library from gradle.
