### ISSUE TITLE
Takes very long time to compress

### ISSUE THREAD

**Issue by varunjain0888** [AbedElazizShe/LightCompressor#28]
Hi ,
I have just run your sample code in my ONE PLUS 6T and it took around 10 min to compress 14 MB of video

**Comment by AbedElazizShe** [comment]
Thank you for raising this issue. Could you please share the video info, as how long is the video? What is the bitrate and frame rate? You can just send a screenshot of the video info.

Thank you

**Comment by AbedElazizShe** [comment]
Please re-open the issue if you're still having problems.
