### ISSUE TITLE
Downloaded videos unable to compress

### ISSUE THREAD

**Issue by khanmujeeb687** [AbedElazizShe/LightCompressor#3]
Both the releases are not working on downloaded videos.

**Comment by AbedElazizShe** [comment]
Could you please add more details to help me fix the issue? Do you get any error? Does the app crash? Could you please share a link of one of these videos for me to debug? Thank you

**Comment by khanmujeeb687** [comment]
The callback onfailure is triggered everytime I select a downloaded video and try to compress it. App is not crashing. I tried it with videos recorded on my phone then it worked well but with downloaded videos the callback onfailure is being triggered.
