### ISSUE TITLE
Smart compression option

### ISSUE THREAD

**Issue by Andoctorey** [AbedElazizShe/LightCompressor#33]
Hi, could you please add option to library to configure compression params. Now it's 30% of bitrate but it's not reliable. Maybe [Telegram code](https://github.com/DrKLO/Telegram/blob/321b75636741cd9b64aaf04fe95b593e7c0cba7b/TMessagesProj/src/main/java/org/telegram/messenger/MediaController.java#L4014) is good ref how to do it right.

**Comment by AbedElazizShe** [comment]
Thank you for your feedback and the reference. I will definitely test that method and release a new version if that is more reliable. I could modify the video quality bitrates as all the values are still experimental..

**Comment by AbedElazizShe** [comment]
I tested the method, the results are not that different from high or medium quality the library offers depending on the original video size and quality. I just added another quality option `VERY_HIGH`. Developers have more control over the output video this way. I am oprn to change the parameters based on suggestions.

I will close this for now and please feel free to open the issue if you have any feedback. 

Thank you
