### ISSUE TITLE
use gradle import online aar , debug run failed

### ISSUE THREAD

**Issue by junguochen** [AbedElazizShe/LightCompressor#34]
Duplicate class org.aspectj.runtime.reflect.AdviceSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.CatchClauseSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.CodeSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.ConstructorSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.Factory found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.FieldSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.InitializerSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.JoinPointImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.JoinPointImpl$EnclosingStaticPartImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.JoinPointImpl$StaticPartImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.LockSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.MemberSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.MethodSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.SignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.SignatureImpl$Cache found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.SignatureImpl$CacheImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.SourceLocationImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.StringMaker found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)
Duplicate class org.aspectj.runtime.reflect.UnlockSignatureImpl found in modules LightCompressor-0.7.2-runtime.jar (com.github.AbedElazizShe:LightCompressor:0.7.2) and aspectjrt-1.8.6.jar (org.aspectj:aspectjrt:1.8.6)

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue. This is happening because you use a dependency relying on isoparser. Could you please try adding the library as follows;

` ``implementation ('com.github.AbedElazizShe:LightCompressor:0.7.3') {
        exclude  group: 'com.googlecode.mp4parser', module: 'isoparser'
    }```

**Comment by junguochen** [comment]
> Thank you for opening this issue. This is happening because you use a dependency relying on isoparser. Could you please try adding the library as follows;
> 
> implementation ('com.github.AbedElazizShe:LightCompressor:0.7.3') {
> exclude group: 'com.googlecode.mp4parser', module: 'isoparser'
> }

**Comment by junguochen** [comment]
thank you, has resolved
