### ISSUE TITLE
Trim video 

### ISSUE THREAD

**Issue by kerlue** [AbedElazizShe/LightCompressor#35]
Hello, Good job with this library. Is it possible to trim a video while it is compressing? For example: 

VideoCompressor.start("/stora...", "...dest/", new CompressionListener() {
            ....
        }, VideoQuality.MEDIUM, true, false, 3, 15);//start = 3s, end = 15sec);

If this feature is not available can you point me in the right direction so I can add this feature myself?

Thanks!

**Comment by AbedElazizShe** [comment]
Thank you for your feedback and the question. Currently, this library only does compression, I might add that feature in the near future if it is requested and if the available video timming libraries miss some important features.
