### ISSUE TITLE
Can we compress more Than Quality.Low 

### ISSUE THREAD

**Issue by digiholicinfotech** [AbedElazizShe/LightCompressor#38]
Hello i want compress my Video more than Low 
at its compressing my video from 70 mb to 7mb with Quality.Low
but i want it to compress 70 to 4mb

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue. 

I can create another video quality `VERY_LOW` for example to give you the size you want, however, are you satisfied with the quality of the video at LOW quality?

**Comment by digiholicinfotech** [comment]
> Thank you for opening this issue.
> 
> I can create another video quality `VERY_LOW` for example to give you the size you want, however, are you satisfied with the quality of the video at LOW quality?

Thank you 
yes the quality is much good at LOW.
and also thanks for this lib its too essay and useful

**Comment by AbedElazizShe** [comment]
I have added the `very_low` quality. Please try version `0.7.5` and let me know if it matches your requirements. 

Thank you
