### ISSUE TITLE
NullPointerException : println needs a message in android

### ISSUE THREAD

**Issue by huynguyennovem** [AbedElazizShe/LightCompressor#4]
- Description:
A bug NPE make app crash: "NullPointerException : println needs a message in android"

- How to fix:
`exception.message`  to `exception.message.toString()`

p/s: @AbedElazizShe : I'd love to contribute to this project. Please grant me a permission to make a pull request. Thanks!

**Comment by AbedElazizShe** [comment]
This is fixed, will be available in next release.
