### ISSUE TITLE
cannot access CoroutineScope

### ISSUE THREAD

**Issue by mishra0007** [AbedElazizShe/LightCompressor#40]
I am getting an error on importing this library

error: cannot access CoroutineScope
                VideoCompressor.start(String.valueOf(contentURI), "//sdcard//Download//", new CompressionListener() {
            
  the class file for kotlinx.coroutines.CoroutineScope not found

Need some help

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue.  Please follow this section https://github.com/AbedElazizShe/LightCompressor#usage. Let me know if you did and still not working.

**Comment by mishra0007** [comment]
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.coroutines}"
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.coroutines}"
On importing these two, I am getting an error which say Could not get unknown property 'Version' for the object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by AbedElazizShe** [comment]
Replace that part with the most recent version.

`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9`
`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9`

**Comment by mishra0007** [comment]
> Replace that part with the most recent version.
> 
> `implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9'`
> `implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9'`

it worked fine
