### ISSUE TITLE
Compress procession Time

### ISSUE THREAD

**Issue by power95031** [AbedElazizShe/LightCompressor#42]
First, very very thanks for this library share ,  very useful and good working.

by the way, some question in my Project 

how can i more fast compress processing? 

( Samsung galaxy S6 )
get video from Album OriginFile Size : 33823052 Byte 
Compress with Quality.VERY_LOW
process time : 21sec
Result file Size close 1/10 byte (very good and i wanted size)

how can faster process time? just use better Phone?

========== example =============

afterFile = new File(this.getFilesDir(), "temp_"+originFile.getName());

VideoCompressor.start( originFile.getPath(), afterFile.getPath(),
                new CompressionListener() {...}, VideoQuality.VERY_LOW );

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue and sorry for the late reply. The pnone itself and the length of the video could be the reason for slightly slow compression time. Please try on different devices and let me know if you have an issue. Feel free to re-open the issue if you have any questions.
