### ISSUE TITLE
Does not work for 4K quality videos

### ISSUE THREAD

**Issue by mkazemian** [AbedElazizShe/LightCompressor#45]
This is the best video compression library I have found, but when I used it, I realized that it could not compress 4K quality videos and it went wrong.

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue. I will have a look and get back to you in a couple of days.

**Comment by AbedElazizShe** [comment]
Thank you for openinig the issue. I tried a many 4k videos and there is no issues, so the problem has to be something else. Could you please let me know what is the Android version and the device(s) you use for testing? An original sample video would be a great help too. Thank you.

**Comment by AbedElazizShe** [comment]
I have tested more and more 4K videos including [this](https://4kmedia.org/spacex-launches-uhd-4k-demo/) and I haven't faced any issues. If you're still facing issues, feel free to re-open the issue. Please specify phone brand and android version if so. Thank you.
