### ISSUE TITLE
The compression operation is very slow

### ISSUE THREAD

**Issue by mkazemian** [AbedElazizShe/LightCompressor#47]
I'm trying to compress 47 MB video but the compression is very slow

Xiaomi Redmi Note 8 with 6 GB of RAM

Video format = mp4
Video size = 47 MB
Video duration = 03:27
resolution = 480*480

Did I write wrong?
`

        txt_check.visibility = View.GONE
        lin_uploadProgress.visibility = View.VISIBLE

       VideoCompressor.start(path, desFile.path, object : CompressionListener {
                override fun onProgress(percent: Float) {

                    val f_percent = percent.toInt()

                    txtUploadedStatus.text = "Compressing ..."

                    runOnUiThread {
                        txtUploadedPercent.text = "$f_percent%"
                        progress_upload.progress = f_percent

                    }

                }

                override fun onStart() {}

                override fun onSuccess() {
                    uploadVideo(caption,desFile)

                }

                override fun onFailure(failureMessage: String) {
                    mlog("compress fail => $failureMessage")
                    txtUploadedStatus.text = "failureMessage"
                }

                override fun onCancelled() {
                    mlog("compress has been cancelled")
                    // make UI changes, cleanup, etc
                }
            }, VideoQuality.MEDIUM, isMinBitRateEnabled = false, keepOriginalResolution = false
        )

    }`

**Comment by AbedElazizShe** [comment]
Thank you for openinig the issue. I noticed a behaviour like that when the video was already compressed such as a whatsapp video. What is the video's bitrate? If you change `isMinBitRateEnabled ` to `true`, can it be compressed?

**Comment by chnouman** [comment]
extremly slow, video size 17mb and taking 35sec
