### ISSUE TITLE
Audio Process Issue

### ISSUE THREAD

**Issue by GobuTranxit** [AbedElazizShe/LightCompressor#49]
In the Compressor processAudio function not working properly. Compressed video file not playing always I am facing audio renderer issue.

**Comment by AbedElazizShe** [comment]
Thank you for openinig the issue. Could you please let me know what is the Android version and the device(s) you use for testing?  An original sample video would be a great help too. Thank you.

**Comment by GobuTranxit** [comment]
I've Tried with Nokia  6.1plus (10) , One Plus 8T(11) and Moto e4Plus(7).  I already shared sample video via E-mail. I think syncing sample timing missing.

**Comment by GobuTranxit** [comment]
Hi Abed,

One more info : I am using ISO Parser = 'com.googlecode.mp4parser:isoparser:1.1.22'

**Comment by AbedElazizShe** [comment]
@GobuTranxit Thank you for the details, I tested the reference video and I don't have an issue.  
I believe you're right, I tried to update my isoparser version to `1.1.22` a few months ago and I had issues with the core classes of the library. If possible, try to match with the version used in the library that is `1.0.6`.

Thank you

**Comment by GobuTranxit** [comment]
Hi AbedElazizShe/LightCompressor,

*Thanks for spending your valuable time*

I've managed with the latest version. I didn't process your audio method.
After frame compress I managed with appending track process without looping
it's working fine.

*Thanks & Regards*
*Gobu CSG*
*Android Developer*

**Comment by AbedElazizShe** [comment]
Thank you for your reply @GobuTranxit, I am glad you managed to fix it. You can always make a pull request if you think something could've been done better. Thank you :D
