### ISSUE TITLE
Video Quality is not good

### ISSUE THREAD

**Issue by dineshchavhan** [AbedElazizShe/LightCompressor#51]
quality issue it blur the video after compression

**Comment by AbedElazizShe** [comment]
Thank you @dineshchavhan for openeing the issue. Could you try to play around with `isMinBitRateEnabled` and `keepOriginalResolution` ? If the video already has a small bitrate or resolution and it is compressed again, it can become blury. If you're sure the video has acceptable bitrate and resolution and it gets blurred, please share a video sample so I can debug and fix any potential issues,

Thank you

**Comment by dineshchavhan** [comment]
thank you for your reply
i am sending both video original and compress please look in it.

this is compressed file is
  24012021060527pm.mp4
<https://drive.google.com/file/d/1tUGr76yFD3TUFoL6iaqoUfpG0cmcJF7y/view?usp=drivesdk>

original file
  testram.mp4
<https://drive.google.com/file/d/1tXmzG10F0jI2Lh2FWdX_ceAjaLfFkiAs/view?usp=drivesdk>

**Comment by AbedElazizShe** [comment]
Thank you @dineshchavhan , please give an access to my email. elaziz.shehadeh@gmail.com

**Comment by AbedElazizShe** [comment]
@dineshchavhan your original video has a very low bitrate of 1975kbps and when compressed it becomes 95kbps.  It seems the video has gone through transcoding somewhere else such as whatsapp. I'd recommend to set `isMinBitRateEnabled` to true and watch for `onFailure`. If you receive this video is too small to be compressed error message, don't compress it so you won't get that bad resolution.

**Comment by dineshchavhan** [comment]
but same video compress with panda video compressor app it become very nice
n less file size.
 see it

  testram panda.mp4
<https://drive.google.com/file/d/1t_tfHo7BdyAx8YKX1NUG0L-rTJF6htQy/view?usp=drivesdk>

**Comment by AbedElazizShe** [comment]
please post the video compresser implementation you're using? Make sure you use VERY_HIGH.

**Comment by dineshchavhan** [comment]
i already set very high still its giving me this blur effect

**Comment by dineshchavhan** [comment]
with very low see the effect and size


  24012021081110pm.mp4
<https://drive.google.com/file/d/1taEWOs5eIV9h7HSTz8LYgxxrakqo3az-/view?usp=drivesdk>

**Comment by AbedElazizShe** [comment]
Just compressed your video using VERY_HIGH quality and it looks like [this](https://drive.google.com/file/d/1DdJkI1OCELN97XR-e10ZqPeqkvZ7i6hm/view?ocid=SK216DHP&osmkt=en-my). Please post your code.

**Comment by dineshchavhan** [comment]
at very_high it give blury effect why, any solution

**Comment by AbedElazizShe** [comment]
If you don't post some code and specify your testing device(s), It is difficult to help you.

**Comment by AbedElazizShe** [comment]
Will close this issue due to inactivity, feel free to re-open.
