### ISSUE TITLE
Does not work for 4K quality videos or return 0 byte video

### ISSUE THREAD

**Issue by vedst** [AbedElazizShe/LightCompressor#53]
This is the best video compression library I have found, but when I used it, I realized that it could not compress 4K quality videos and it went wrong. It works for some video and returned 0-byte video for some.

Many videos from the below website are not working.

https://www.pexels.com/video/5645774/

FYI: I tested on the demo APK you attached on Github.

Device: Google Pixel 4a OS 11, Samsung s10 OS 10 (NOT working on these devices) but the same video worked on Pixel2xl device.

inputFormat --> {has-sdtp=1, track-id=1, level=65536, mime=video/avc, frame-count=1021, profile=8, language=und, color-standard=1, display-width=2160, track-fourcc=828601953, csd-1=java.nio.HeapByteBuffer[pos=0 lim=9 cap=9], color-transfer=3, durationUs=40840000, display-height=4096, width=2160, color-range=2, max-input-size=6291456, frame-rate=25, height=4096, csd-0=java.nio.HeapByteBuffer[pos=0 lim=32 cap=32]}

Exception i get --> java.lang.NullPointerException on line number 
Risky code
val decoderName = MediaCodecList(REGULAR_CODECS).findDecoderForFormat(inputFormat)
 ---->  decoder = MediaCodec.createByCodecName(decoderName) <-------

because decoderName is null (MediaCodecList can not find decoder according inputformat) inpuformat string write above

**Comment by vedst** [comment]
@AbedElazizShe Can you please help me on this?

**Comment by AbedElazizShe** [comment]
@vedst  I have tested the video from the provided link on pixel 4a and it is working fine. It seems you're using an older version of the library, please update to the latest version 0.7.9 and let me know if you still face the problem.

**Comment by AbedElazizShe** [comment]
I will close this issue, feel free to re-open if you test in the new version and you still have the issue.

**Comment by jimibilibob** [comment]
@AbedElazizShe I have the same problem with the latest version 1.3.2
