### ISSUE TITLE
Compress video file don't have extension

### ISSUE THREAD

**Issue by mbpatel6245** [AbedElazizShe/LightCompressor#58]
I have checked the library successfully compressed the video file but the compressed file does not have extensions so in that case, we need to manually set extensions then we can check the video. 

can anyone help me to get the default extension that I have to pick the video (like mp4, mov, avi, wmv etc) and compress video give the same extension?

**Comment by AbedElazizShe** [comment]
@mbpatel6245 thank you for opening this issue. That's a strange problem that I haven't faced before. Could you please try the apk sample in README? Please provide details like the device you use, the Android version, and maybe the video you use to compress. Thank you.

**Comment by AbedElazizShe** [comment]
The library will give the output as .mp4. What is the scenario where you got a no extension file? 

I will close this issue due to inacivity and as the library works with .mov extension for examp,le. Feel free to reopen.

**Comment by s4cha** [comment]
Hey @AbedElazizShe, first, thank you for taking the time to share such a great tool, this is very appreciated !
I wanted to add on to @mbpatel6245 issue, I just encountered the same.
Here is my 
**initial uri**
/storage/emulated/0/DCIM/Camera/VID_20220125_141444.mp4 OK
**success uri**
/storage/emulated/0/Android/data/com.octopepper.yummypets/files/YummypetsVideoCompression/1643116799636_

As you can see the second one lost the .mp4 extension. @mbpatel6245 have you found the underlying issue?
