### ISSUE TITLE
Video cant compressor when newWith or newHeight is odd

### ISSUE THREAD

**Issue by kientrung0412** [AbedElazizShe/LightCompressor#59]
Not all devices,  It happens on redmi note 8, miui 12

**Comment by kientrung0412** [comment]
> Not all devices, It happens on redmi note 8, miui 12

**Comment by AbedElazizShe** [comment]
@kientrung0412 thank you for the details, I will investigate that and will notify you when the fix is added.

**Comment by AbedElazizShe** [comment]
I have added a check to ensure this does not happen, It will be released soon.

**Comment by AbedElazizShe** [comment]
Issue fixed in version 0.8.1. Please let me know if you still have the issue. You can close the task if the problem is solved.
