### ISSUE TITLE
Some video not to be compress

### ISSUE THREAD

**Issue by DaxeshV** [AbedElazizShe/LightCompressor#6]
Getting message like this video cannot be compressed. Working only some specific videos.

**Comment by AbedElazizShe** [comment]
Thank you for openning the issue. 
The library compresses videos above ceartain quality to avoid recompessing same video again and again resulting in a bad quality. 

If the bitrate is less than 2mbps, it won't be compressed. Please let me know if this value should be adjusted.

**Comment by DaxeshV** [comment]
Sorry but i selected HD 200 mb video from my gallery and it not compress getting error on many video also.

**Comment by AbedElazizShe** [comment]
could you please share one of these videos so I can investigate ?

**Comment by DaxeshV** [comment]
Ya sure. I will send it
