### ISSUE TITLE
cannot able to read the duration parameter in meta data with out using codec 

### ISSUE THREAD

**Issue by hidash** [AbedElazizShe/LightCompressor#62]
After .mp4 Video Compression Video cannot able ** to  read the duration parameter in meta data with out using codec** ,also the desired out is in fine but cannot able to open up with out codec, 
![Capture](https://user-images.githubusercontent.com/8371370/110519240-14f75200-8133-11eb-80c1-70d6e875d919.PNG)

any option to solve it ?

**Comment by AbedElazizShe** [comment]
@hidash  thank you for opening this issue. Does it happen in multiple devices ? Could you please share the devices you're using?

**Comment by hidash** [comment]
@AbedElazizShe  yes, I have using Android 10 in Redmi Note 7 Pro , also checked in Samsung Devices

**Comment by hidash** [comment]
@AbedElazizShe can you able to solve this issue, i hope so, thank you

**Comment by hidash** [comment]
Real me 2
Redmi Note 7 Pro
Samsung M31S
i have checked with thee phone

**Comment by hidash** [comment]
@AbedElazizShe  Hello, in the server side trying to load duration parameter from compressed file, using this plugin, 
_https://www.npmjs.com/package/get-video-duration_
and can't able to read it, getting a response  _Error: No duration found!_ 

can you help me please, if you got any idea please....

**Comment by AbedElazizShe** [comment]
@hidash I have been investigating this for a while, I will notify you when it is figured out. Thank you.

**Comment by AbedElazizShe** [comment]
@hidash please try with the latest version of the library, I believe it is fixed. Feel free to reopen if you still have a n issue.
