### ISSUE TITLE
No audio after compress

### ISSUE THREAD

**Issue by Joshuaj2804** [AbedElazizShe/LightCompressor#63]
On latest version, after compressing, playing back on phones always results in audio codec not supported error, and on Chrome (after upload the video to server), the video doesn't play

**Comment by AbedElazizShe** [comment]
@Joshuaj2804 thank you for opening the issue. 

Could you provide more information on how you play the video? what kind of servers? for example if I use aws S3, would I have the same issue? And can you play the video if uploaded to google drive?  I just want to produce the scenario so I can ensure it's fixed.

Thank you.

**Comment by VikasTiwari199915** [comment]
I am having the same issue, there is no sound or sound track is not supported by any player, if i play the compressed video in android phone there is no sound, i fi play it in my laptop in vlc player it says:
**Codec not supported
VLC could not decode the format "mp4a" (MPEG AAC Audio)**
![Screenshot 2021-03-23 at 4 01 17 AM](https://user-images.githubusercontent.com/44534116/112066488-6fa99880-8b8c-11eb-8b0e-331ad4afc414.png)

**Comment by VikasTiwari199915** [comment]
ok, i was searching some way to fix this, and found a solution that works for me.
implementation 'com.googlecode.mp4parser:isoparser:1.1.22'
changing the version of isoparser from latest version to 1.0.6 fixed the audio issue for me.

**Comment by AbedElazizShe** [comment]
@VikasTiwari199915 Thank you for your input. Yes correct, the compressor requires 1.0.6 isoparser. Updating to the lastest version is a huge, but will be done at some point this year.

**Comment by Shubham-Mollatech** [comment]
hi @AbedElazizShe 
I tried with both version but having same issue
implementation "com.googlecode.mp4parser:isoparser:1.1.22"
implementation "com.googlecode.mp4parser:isoparser:1.0.6"
