### ISSUE TITLE
Library not working in android 11 

### ISSUE THREAD

**Issue by nitininfoenum** [AbedElazizShe/LightCompressor#65]
Unable to  creating directory using android 11 .It gives error when pass desPath

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue. Please refer to [sample app](https://github.com/AbedElazizShe/LightCompressor/blob/7afa700c3b2d7d79bebf33a79acd1f6800bd13d7/app/src/main/java/com/abedelazizshe/lightcompressor/MainActivity.kt#L206) on how you can save media in Android 11. 

Let me know if you still have an issue.
