### ISSUE TITLE
ios:Failed to Compress

### ISSUE THREAD

**Issue by pha141** [AbedElazizShe/LightCompressor#69]
Medium->low(bit rate disabled) :: I recorded the video with UIImagepickercontroller with video quality medium. try to the compress video with low. thrown error  as 
"The provided bitrate is smaller than what is needed for compression try to set isMinBitRateEnabled to false".

I found two solutions but both are not feasible for me :

1.high-> low (bit rate disabled):: recording video quality with higher .Then bit rate enough but size is getting very hug . same combination worked well (medium->low) (bit rate disabled) when I tried with a custom recording compressor it's got sucess.
2.Medium->low(bit rate enabled):: compressor getting success but output video quality is very poor

Could you help with other alternatives??

**Comment by AbedElazizShe** [comment]
@pha141 I think this issue should be opened somewhere else. This is the Android library. I am gonna close it,
