### ISSUE TITLE
Mirror effect

### ISSUE THREAD

**Issue by juslam** [AbedElazizShe/LightCompressor#70]
I tried to use this plugin and the results are like the image below. .... the result was flipped... 

![image](https://user-images.githubusercontent.com/11010081/113640945-28a0c480-96af-11eb-850e-d949bac73362.png)

**Comment by AbedElazizShe** [comment]
@juslam Thank you for opening this issue. This is very interesting, I have never face this before. Could you please share:

- The device model
- The version of the library use.
- The original video if possible.

Thank you.
