### ISSUE TITLE
Failed to resolve: com.github.AbedElazizShe:LightCompressor:0.9.0

### ISSUE THREAD

**Issue by Yogesh9900** [AbedElazizShe/LightCompressor#71]
I am trying to  add LightCompressor:0.9.0 library in app gradle.
    implementation 'com.github.AbedElazizShe:LightCompressor:0.9.0'

Getting issue: Failed to resolve: com.github.AbedElazizShe:LightCompressor:0.9.0

My kotlin version is:  "1.4.21"

**Comment by bmarty** [comment]
Hello @Yogesh9900, have you done https://github.com/AbedElazizShe/LightCompressor#gradle ?

**Comment by Yogesh9900** [comment]
> Hello @Yogesh9900, have you done https://github.com/AbedElazizShe/LightCompressor#gradle ?

Yes.

**Comment by AbedElazizShe** [comment]
@Yogesh9900 thank you for opening the issue. I belive this issue happens when  maven { url 'https://jitpack.io' } is not added to the project's build.gradle as @bmarty mentioned. Could you please share a snippet of the code of build.gradle?

**Comment by AbedElazizShe** [comment]
@Yogesh9900 I am glad it is working for you.

**Comment by aleks-walker** [comment]
I added 
`maven(url = "https://jitpack.io")`
to the build.gradle.kts but still get an error 
`Failed to resolve: com.github.AbedElazizShe:LightCompressor:0.9.2`

**Comment by aleks-walker** [comment]
> Hello.
> I added
> `maven(url = "https://jitpack.io")`
> to the build.gradle.kts but still get an error
> `Failed to resolve: com.github.AbedElazizShe:LightCompressor:0.9.2`

@AbedElazizShe the problem is still present with 0.9.3

**Comment by aleks-walker** [comment]
My problem was that Android Studio Arctic Fox (beta channel) doesn't create "allprojects" in build.gradle file
these will help:
https://stackoverflow.com/questions/33058358/jitpack-io-failed-to-resolve-github-repo
https://stackoverflow.com/questions/66475730/in-android-studio-arctic-fox-canary-8-the-app-level-build-gradle-does-not-gener
