### ISSUE TITLE
No Audio After Compress the video 

### ISSUE THREAD

**Issue by Shubham-Mollatech** [AbedElazizShe/LightCompressor#73]
hi @AbedElazizShe
I tried with both version but having same issue
implementation "com.googlecode.mp4parser:isoparser:1.1.22"
implementation "com.googlecode.mp4parser:isoparser:1.0.6"
have any one resolved this issue?

**Comment by gandhiishan624** [comment]
Yes, I facing same issue. have any solution??

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue. Please share the devices you're using for testing as I don't have any issues on my testing devices. Anyway, with 1.1.22 there will be no audio, however, 1.0.6 which this library uses, should work just fine.

**Comment by gandhiishan624** [comment]
Actually Audio issue with Exo-Player play. After Compress Video process, The Audio not playing in Exo-Player and getting Exo-Player audio error. but When you export it to the computer and try to play in the computer media player, It is working fine.
