### ISSUE TITLE
Permission for android 11

### ISSUE THREAD

**Issue by fereshteh-jvz** [AbedElazizShe/LightCompressor#74]
Hi @AbedElazizShe 

Write persmission is not working for android 11.. So compression fails and says "Source path: $source can be invalid! or you don't have READ_EXTERNAL_STORAGE permission" even though I have the READ permission

I am using 0.9.0 version

Please help on this

**Comment by fereshteh-jvz** [comment]
Please this is urgent
Because from 5th of may google play doesn't allow WRITE Persmission and requestLegacyExternalStorage=true must be removed.

**Comment by bijosh-accubits** [comment]
Hi,

I am also facing the same issue. Is there any fix available for this? Can you please help?

**Comment by AbedElazizShe** [comment]
Thank you for opening this issue.

I believe you can remove `requestLegacyExternalStorage=true` and change the permission to:

```
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="28" />
```

Does that work ?

**Comment by PositronPiercer** [comment]
Hi, 
I was getting the same error. Passing absolute path worked for me
```
srcPath = src_file.absolutePath, 
destPath = des_file.absolutePath
```

**Comment by lancer1268** [comment]
Hi,
the sample app didn't work on my Samsung A60 with Android 10 and the error message was what @fereshteh-jvz mentioned.

IMHO, the uri of the selected video should be used in the contentProvider, otherwise it would have permission issue when read from its path.

I modified the function `Compressor.compressVideo` and then the sample app works
- replace `setDataSource` of `MediaMetadataRetriever` and `MediaExtractor` with the one that accepts a `Context` and a `Uri` instead of a `String`
- skip checking `file.canRead()` when `context` and `srcUri` are provided

**Comment by bijosh-accubits** [comment]
Hi @lancer1268 , Thanks for the help. I tried exactly as you said, but it's not working. Is there anything to do other than this?

**Comment by bijosh-accubits** [comment]
> Thank you for opening this issue.
> 
> I believe you can remove `requestLegacyExternalStorage=true` and change the permission to:
> 
> ```
>     <uses-permission
>         android:name="android.permission.WRITE_EXTERNAL_STORAGE"
>         android:maxSdkVersion="28" />
> ```
> 
> Does that work ?
> 
> Note: refer to to the sample app.

Still not working on Android 10 for me. Please help

**Comment by lancer1268** [comment]
> > Thank you for opening this issue.
> > I believe you can remove `requestLegacyExternalStorage=true` and change the permission to:
> > ```
> >     <uses-permission
> >         android:name="android.permission.WRITE_EXTERNAL_STORAGE"
> >         android:maxSdkVersion="28" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does that work ?
> > Note: refer to to the sample app.
> 
> Still not working on Android 10 for me. Please help

I forgot to mention that you might need to change the `desFile` in `MainActivity.saveVideoFile`.
Otherwise you might encounter the error `java.io.IOException: Permission denied`.

One possible solution is to use
```
// val desFile = File(downloadsPath, videoFileName)
val desFile = File.createTempFile("sample_prefix", ".mp4", cacheDir)
```

Hope this would help.

**Comment by fereshteh-jvz** [comment]
![WhatsApp Image 2021-06-17 at 2 01 20 PM](https://user-images.githubusercontent.com/46874710/122370899-aff29a00-cf74-11eb-96ba-7913ec40612f.jpeg)
 Hi @AbedElazizShe 
 Thanks for your reply. This is your sample app on android 10 and still shows the same error.
 I believe @lancer1268 solution will work on this issue.

**Comment by AbedElazizShe** [comment]
@lancer1268 thank you for the great details. I managed to fix the issue based on your inputs. 

Regarding the destination file in your activity, you can just replace `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)` with `applicationContext.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS)`

I will release a fix shotrly.

**Comment by AbedElazizShe** [comment]
Please try in version 0.9.3.
