### ISSUE TITLE
[Feature request] Let the user choose bitrate/width/height

### ISSUE THREAD

**Issue by axionnneeeel** [AbedElazizShe/LightCompressor#75]
Hi.

Would it be possible to add the feature to choose by ourselves bitrate/width/height instead of giving some predefined quality types ?

**Comment by AbedElazizShe** [comment]
@axionnneeeel thank you for the request, I will work on adding that within 2 weeks.

**Comment by AbedElazizShe** [comment]
Added support in version 0.9.1. Please let me know if you have any issues or questions.

**Comment by AbedElazizShe** [comment]
Hi @axionnneeeel i added them back, will release soon.
