### ISSUE TITLE
During Compress Issue

### ISSUE THREAD

**Issue by abhayjaiswal** [AbedElazizShe/LightCompressor#76]
I am getting these logs in logcat but give the response in onSuccess() . Video is not compress when i got this logs 

**1st Logs:-** /MediaExtractor: Trace connect 0x8e618e40 0x8dc4d4c0
/ACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
/ACodec: signalError(omxError 0x80001001, internalError -1010)
MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
MediaCodec: configure failed with err 0xfffffc0e, resetting...
E/Compressor: Error 0xfffffc0e

**2nd Logs :-** 
/MediaExtractor: Trace connect 0x933cc580 0x92d6b000
/ACodec: OMX.qcom.video.encoder.avc does not support profile 10000 @ level 10000
E/ACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -61
/ACodec: signalError(omxError 0x80001001, internalError -61)
/MediaCodec: Codec reported err 0xffffffc3, actionCode 0, while in state 3
/MediaCodec: configure failed with err 0xffffffc3, resetting...
/Compressor: Error 0xffffffc3

**Comment by Nikki-Gunani** [comment]
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
E/ACodec: [OMX.google.h264.encoder] configureCodec returning error -61
E/MediaCodec: Codec reported err 0xffffffc3, actionCode 0, while in state 3
E/MediaCodec: configure failed with err 0xffffffc3, resetting...
I/OMXClient: IOmx service obtained
E/Compressor: Error 0xffffffc3
I/BpBinder: onLastStrongRef automatically unlinking death recipients: android.media.IResourceManagerService

And yet it call the onSuccess callback..
E/Compression: OnSuccess

**Comment by AbedElazizShe** [comment]
Sorry for late reply and thank you for opening the issue. The functionlity of this library depends alot on the device you're using. I'd appriciate if you can share which devices and which android version they're running so I can narrow down the cause. Thank you.

**Comment by abhayjaiswal** [comment]
Hi AbedElazizShe/LightCompressor

I am using oreo 8.1 and redmi device

**Comment by AbedElazizShe** [comment]
Thank you for the quick reply. Could you please try version 0.9.1 ?

**Comment by abhayjaiswal** [comment]
Yes I have latest version of library.

**Comment by AbedElazizShe** [comment]
@abhayjaiswal thank you for the confirmation. I have tried on almost all devices on browserstack and couldn't reproduce the issue. Could you please do me a favor and try the sample apk in README, and let me know if the issue is happening? 

You might as well share a sample video so I can try on my side. The issue could be related to a specific video configurations.

Thank you.

**Comment by AbedElazizShe** [comment]
Please try in version 0.9.3 and let me know if it is fixed.

**Comment by shaktis110** [comment]
sir its not fixed same error on pixel 3a api 28 android 9

**Comment by shaktis110** [comment]
even the demo apk not working getting same error as mentioned above

**Comment by shaktis110** [comment]
Recorded videos are compressed, the problem is only with downloaded videos

**Comment by AbedElazizShe** [comment]
Potential duplication of #81
