### ISSUE TITLE
Error start failed

### ISSUE THREAD

**Issue by nailshakurov** [AbedElazizShe/LightCompressor#78]
![image](https://user-images.githubusercontent.com/11345578/123671806-baa00f80-d84f-11eb-9950-ba457f98d1f3.png)

**Comment by AbedElazizShe** [comment]
@nailshakurov thank you for opening this issue. It seems you're not using the latest version of the library, could you please confirm that?

In addition, please try the sample app where you can find a link to it in README file. If you have any issue, please share your Android version and the Android phone you're using for testing. 

Thank you.

**Comment by AbedElazizShe** [comment]
Please try version 0.9.3 and let me know if you have any issues.

**Comment by nailshakurov** [comment]
> Please try version 0.9.3 and let me know if you have any issues.

No, the problem is not the version. I used the new version didn't help.
Error: Startup error failed
It comes down due to the fact that mediacodec, I use it in two places in parallel.

The problem in the library is that the catch block does not handle the exception correctly. An error comes, but the result from the library is successful - this is not true.

**Comment by AbedElazizShe** [comment]
@nailshakurov thank you for pointing this out, i improved it.
