### ISSUE TITLE
compression  Error 

### ISSUE THREAD

**Issue by shaktis110** [AbedElazizShe/LightCompressor#81]
device - pixel 3a
android 9
api 28

Recorded videos are compressed, the problem is only with downloaded videos from internet giving error  
 configureCodec returning error -61.

tested on demo.apk 0.9.2  and also with 0.9.3

**Comment by AbedElazizShe** [comment]
@shaktis110 thank you for opening this issue. Could you please share one of the videos so I can debug?

**Comment by shaktis110** [comment]
thank you so much for your precious time sir 
here is the link : https://drive.google.com/file/d/1XDLZIxQS96bsyjJO7cNONu2j-G1a1n-y/view?usp=sharing

**Comment by shaktis110** [comment]
thank you so much for your precious time sir.
here is the link :https://drive.google.com/file/d/1Xk9b-oaFyhf15Tv8lK2kUdNU0hTzCF5F/view?usp=sharing

**Comment by shaktis110** [comment]
![Screenshot_1626844830](https://user-images.githubusercontent.com/38592947/126436433-33295577-38fb-45d2-a15d-03734b1eea66.png)

**Comment by shaktis110** [comment]
![IMG20210721105059](https://user-images.githubusercontent.com/38592947/126436493-dbc7d766-253f-4a74-8c97-6507f210068f.jpg)

**Comment by AbedElazizShe** [comment]
@shaktis110 thanks a lot man, it has to be device specific with the OMX encoder, could you please let me know of your testing device?

**Comment by shaktis110** [comment]
Sir I am testing on emulator pixel 3a

**Comment by AbedElazizShe** [comment]
That emulator does not have a hardware encoder, and there isn't much I can do. Please try physical devices or things like GenyMotion or browserStack for testing.

**Comment by shaktis110** [comment]
Thanks sir , I'll check it out.

**Comment by AbedElazizShe** [comment]
@shaktis110 let me try to add a solution to use software encoders. I need to play around with profile levels, give me a few minutes to try.

**Comment by shaktis110** [comment]
Thank you sir

**Comment by AbedElazizShe** [comment]
it's working now, will publish a release shortly. Thanks for the valuable details.

**Comment by shaktis110** [comment]
I'm glad to have your help sir

**Comment by shaktis110** [comment]
thank you so much sir when will i expect new release

**Comment by AbedElazizShe** [comment]
Released, version 0.9.4. Please close the issue if it works fine.

**Comment by shaktis110** [comment]
Respected sir, I have tested the new release and it is working perfectly.
Thank you very much sir for your valuable time.
