### ISSUE TITLE
Does not work without JCenter

### ISSUE THREAD

**Issue by ShaQib07** [AbedElazizShe/LightCompressor#87]
All working ok, but if I remove JCenter from the repository, it doesn't compile anymore.
I've attached the logs as well.
![image](https://user-images.githubusercontent.com/32202397/129916651-ba32c4b8-de1d-47c7-8aa3-666ce67b8820.png)
```
 > Could not find net.ypresto.qtfaststartjava:qtfaststart:0.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/ypresto/qtfaststartjava/qtfaststart/0.1.0/qtfaststart-0.1.0.pom
       - https://repo.maven.apache.org/maven2/net/ypresto/qtfaststartjava/qtfaststart/0.1.0/qtfaststart-0.1.0.pom
       - https://jitpack.io/net/ypresto/qtfaststartjava/qtfaststart/0.1.0/qtfaststart-0.1.0.pom
     Required by:
         project :app > com.github.AbedElazizShe:LightCompressor:0.9.6
```

**Comment by AbedElazizShe** [comment]
@ShaQib07 thank you for opening this issue. I have remove JCenter() and i am using mavenCentral() instead. Would that solve your issue?

**Comment by AbedElazizShe** [comment]
@ShaQib07 please try version 0.9.7 and let me know if it's working as expected. Thank you.
