### ISSUE TITLE
InputStream as Output/Destination Path

### ISSUE THREAD

**Issue by dev-sareno** [AbedElazizShe/LightCompressor#89]
On modern Android OS (e.g. Android 11+), sometimes, you have to use [MediaStore](https://developer.android.com/reference/android/provider/MediaStore) for choosing the target file to write but, it gives you an [Uri](https://developer.android.com/reference/android/net/Uri) rather than a [File](https://developer.android.com/reference/java/io/File). We can write on that Uri through [Context#getContentResolver().openInputStream(uri)](http://developer.android.com/reference/android/content/ContentResolver.html#openInputStream%28android.net.Uri%29) but it returns an [InputStream](https://developer.android.com/reference/java/io/InputStream) hence, why it is useful as Write Path rather than alternatives.

**Comment by AbedElazizShe** [comment]
@dev-sareno Thank you for opening this issue and for the provided details. I haven't explored the Android 11+ changes yet regarding media handling. I will look into that and improve the library accordingly, i will make this suggestion as priority 1 and will inform you when it is done.

Thank you

**Comment by dev-sareno** [comment]
My bad, I was pertaining to OutputStream as the Write Path parameter and not InputStream.
