### ISSUE TITLE
Licences

### ISSUE THREAD

**Issue by febg11** [AbedElazizShe/LightCompressor#9]
I wanted to ask a couple of questions before I try using your library. 

1) Does this use any FFMPEG (L)GPL licensed code or patented algorithms by MPEG LA?

2) As this is licensed under apache 2.0 am I okay to use this in a commercial project?

Thanks a lot :)

**Comment by AbedElazizShe** [comment]
Thank you for raising this question. 

I have added a [LICENSE ](https://github.com/AbedElazizShe/LightCompressor/blob/master/LICENSE) file to describe how this library can be used.

**Comment by febg11** [comment]
Oh I can't use this now you have made it gpl. That is a shame :/

**Comment by AbedElazizShe** [comment]
It is not that I wanted to, rather than, had to. I am using a GPL class in my library. I could't find a way around this. Thank you for opening this issue which gave me the chance to fix the license.

**Comment by febg11** [comment]
Oh okay. Could I ask what gpl library caused this so I don't accidentally use it.

**Comment by AbedElazizShe** [comment]
Sure, it is this [class](https://github.com/AbedElazizShe/LightCompressor/blob/master/lightcompressor/src/main/java/com/abedelazizshe/lightcompressorlibrary/MP4Builder.java)

**Comment by nishiloxit** [comment]
@AbedElazizShe Can you answer the 1st question here? Does this library use FFMPEG?

**Comment by AbedElazizShe** [comment]
@nishiloxit no it isn't.
