### ISSUE TITLE
Audio Lost 

### ISSUE THREAD

**Issue by Amir-ByteGrowth** [AbedElazizShe/LightCompressor#90]
When we compress video it losses its audio

**Comment by Amir-ByteGrowth** [comment]
will any one else help to solve this issue?

**Comment by AbedElazizShe** [comment]
@Amir-ByteGrowth thank you for opening this issue. Can you provide more details, phone brand, android version, library version, and perhaps a sample video so I can debug.

Thanky you

**Comment by Amir-ByteGrowth** [comment]
i am using Huawei Honor 8x Model JSN-L22 Version 10.0, i am using library from github sample code. i dont know its version.

**Comment by Amir-ByteGrowth** [comment]
i sent an email containing video  on mentioned email you can check it from there

**Comment by Amir-ByteGrowth** [comment]
its fixed. it is due to mp4 parser . thank you for cooperation @AbedElazizShe

**Comment by kalasaceo** [comment]
I too have this same problem and i have not used mp4 parser.The output video is compressed but no audio.

**Comment by pankaj9717** [comment]
> cooperation

can you please explain how you resolve this issue
