### ISSUE TITLE
Compression takes too much time 

### ISSUE THREAD

**Issue by emrisb** [AbedElazizShe/LightCompressor#94]
Firstly, thanks for this great library.
I am trying compress a video, but it takes too much time. Generally i come across this issue in big sized videos.
example video spec:
size: 276mb 
duration: 00:59 sec
After I tried sample app, compress time average was 70 sec and size 111 mb

**Comment by AbedElazizShe** [comment]
@emrisb Thank you for opening this issue. I am working on improving the speed of compression. At the moment, the library could be a bit slow with big video sizes and hopefully this would be improved in the near future.

Thank you.
