### ISSUE TITLE
Size is the same for every quality

### ISSUE THREAD

**Issue by UrbanFercec** [AbedElazizShe/LightCompressor#95]
First of all - thank you for this amazing library. I belive it's the best there is on video compression on Android!

However, I have found an very strange bug - whenever I compress video, no matter the quality, I always get back the same size of the video. I get this issue if I leave all the rest of the fields empty of I leave them as default.

Am I doing something wrong here or is this worth investigating?

**Comment by AbedElazizShe** [comment]
@UrbanFercec thank you for the kind feedback and I aplogise for the late reply.

If you check the video details on, let's say, windows or mac, is it showing the same size? I noticed that Android sometimes show the old size and configuration, which in fact is not correct. It has to do with how the original video was written to the folder after compression. 

Could you please check on that and confirm?

Thanks a lot.

**Comment by minshoki** [comment]
Call the function after conversion is complete.

`contentResolver.update()`
