### ISSUE TITLE
Disable audio while compression

### ISSUE THREAD

**Issue by gangergarry** [AbedElazizShe/LightCompressor#96]
Hi @AbedElazizShe, Thanks for making this fabulous library. could you please guide me on how can I disable the audio of the video with compression? and if this functionality is not available as of now, do you have any plans to do so?

**Comment by AbedElazizShe** [comment]
@gangergarry @parulgarg004 i apologise for the late reply. I have added the feature, you just need to pass the following in configuration.

disableAudio = true

I will release a new version soon.

Thank you.

**Comment by AbedElazizShe** [comment]
Version 1.0.0 has this feature. Thank you.

**Comment by parulgarg004** [comment]
@AbedElazizShe ThankYou so much
