### ISSUE TITLE
Not Compressing by Configuration Android 12

### ISSUE THREAD

**Issue by MohammedNadil** [AbedElazizShe/LightCompressor#99]
Hi, 
I got an issue in Android 12
its working fine on other OS Versions

In Android 12   even I put any quality the size is fixed after compression
even I put a fixed bitrate after compression is same size.

I used latest version 1.0.0 
also used 0.9.6 with fixed width height and all other choices but result is the same 
this issue is only on android 12. 

normally its 50mb to 15mb

in android 12 it goes as 50mb to 40mb  or 50mb to 60mb sometimes

I tested in Android 12 emulator  ,  pixel 5 and 4 and confirmed issue is same

any help or suggestion would be grateful  - Thankyou

**Comment by AbedElazizShe** [comment]
@MohammedNadil Thank you for opening this issue. Have you tried o physical devices? Could you please share a sample video so I can try on my side and figure out the issue.

I am using android 12 and I don't face the issue for some reason.
![Screenshot_20211211-234105](https://user-images.githubusercontent.com/20614470/145683151-a5659b01-68f0-40ae-a6b4-f05467649c69.png)

![Screenshot_20211211-234054](https://user-images.githubusercontent.com/20614470/145683156-376df296-d4a6-4f64-9b36-33d01a758d00.png)

**Comment by MohammedNadil** [comment]
The clip is created using HBRecorder with settings as below. 

  Library =  https://github.com/HBiSoft/HBRecorder
  Settings =

            hbRecorder?.enableCustomSettings()
            hbRecorder?.setVideoEncoder("H264")
            hbRecorder?.recordHDVideo(true)
            hbRecorder?.setScreenDimensions(1280, 720)

recorded for about 4min video clip and 
then its compressed to Low Quality  which result in 15-20mb range normally. but in Android 12 size remains original size range sometimes higher.

**Comment by AbedElazizShe** [comment]
Hi @MohammedNadil , please share a video with me to try. 

Thank you.
